use strict;
use warnings;

use Test::More;

use lib '../dbio/lib', 'lib';

my ($dsn, $user, $pass) = @ENV{map { "DBIOTEST_PG_${_}" } qw/DSN USER PASS/};

plan skip_all => 'Set DBIOTEST_PG_DSN, _USER and _PASS to run this test'
  unless $dsn && $user;

require DBI;

my $dbh = DBI->connect($dsn, $user, $pass, {
  AutoCommit => 1,
  RaiseError => 1,
  PrintError => 0,
});

my $schema_name = 'dbio_loader_live';

END {
  return unless $dbh;
  eval { $dbh->do("DROP SCHEMA IF EXISTS $schema_name CASCADE") };
}

$dbh->do("DROP SCHEMA IF EXISTS $schema_name CASCADE");
$dbh->do("CREATE SCHEMA $schema_name");
$dbh->do("CREATE TYPE $schema_name.role_type AS ENUM ('admin', 'user')");
$dbh->do(qq{
  CREATE TABLE $schema_name.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    role $schema_name.role_type NOT NULL DEFAULT 'user'
  )
});
$dbh->do(qq{
  CREATE UNIQUE INDEX users_lower_email_idx
    ON $schema_name.users (lower(email))
});
$dbh->do(qq{
  CREATE INDEX users_role_partial_idx
    ON $schema_name.users (role)
    WHERE role <> 'user'
});
$dbh->do(qq{
  ALTER TABLE $schema_name.users ENABLE ROW LEVEL SECURITY
});
$dbh->do(qq{
  CREATE POLICY users_self
    ON $schema_name.users
    USING (id > 0)
});

{
  package DBIO::Test::PgLoader::Schema;
  use base 'DBIO::Loader';

  __PACKAGE__->loader_options(
    db_schema      => [$schema_name],
    loader_class   => 'DBIO::PostgreSQL::Loader',
    use_namespaces => 1,
    naming         => 'current',
  );
}

my $schema = DBIO::Test::PgLoader::Schema->connect($dsn, $user, $pass);

ok($schema->can('source'), 'loader returned a connected schema');
is_deeply([$schema->sources], ['Users'], 'table loaded from dedicated schema');

my $source = $schema->source('Users');
my $class  = $source->result_class;

ok($class->can('pg_schema'), 'PostgreSQL::Result component loaded');
is($class->pg_schema, $schema_name, 'schema qualifier recorded');

my $indexes = $class->pg_indexes;
ok(exists $indexes->{users_lower_email_idx}, 'expression index captured');
ok(exists $indexes->{users_role_partial_idx}, 'partial index captured');

my $rls = $class->pg_rls;
ok($rls->{enable}, 'RLS enable flag captured');
ok(exists $rls->{policies}{users_self}, 'RLS policy captured');

done_testing;
